### ISSUE TITLE
HTTP/2 - The Evolution Continues

### ISSUE THREAD

**Issue by DesmondANIMUS** [wwgdelhi/Talks#1]
- [x] Title: HTTP/2 - The Evolution Continues
- [x] Short Abstract: The talk will cover the latest seventh layer protocol HTTP/2, shortcomings of HTTP/1.x & how we've overcome them over the course of years including a small demo in Golang
- [x] Full description/topics covered: History & Theory related to the HTTP protocol. An example implementation of HTTP/2 & HTTP/2 server push.
- [x] Duration: 20-30 Minutes
- [x] Level of expertise required: Beginner
- [x] Special requirements: Laptop ( **not** compulsory though )

**Comment by RN0311** [comment]
@DesmondANIMUS : We're excited for your lightning talk session.Can you please upload slides prepared for that, will be easier for us to evaluated!
Thanks!

**Comment by DesmondANIMUS** [comment]
Sure thing :)

Here's the link: https://github.com/DesmondANIMUS/http2-lightning-talk
