### ISSUE TITLE
Why GoLang?

### ISSUE THREAD

**Issue by Jap-Leen** [wwgdelhi/Talks#2]
1. Title: Why GoLang?
 2. Short Abstract: The talk will cover some interesting facts and figures regarding GoLang, also covering some salient features about Go, like Concurrency and Goroutines.
 3. Duration: 10-15 Minutes
 4. Level of expertise required: Beginner

Here is a link to the slides I have prepared for the same: https://github.com/Jap-Leen/Lightning-Talk--Women-Who-Go-Delhi/blob/master/final.pdf

**Comment by RN0311** [comment]
@Jap-Leen : Can you please update the link, it is still not accessible.
Thanks! :)

**Comment by Jap-Leen** [comment]
@RN0311 Done! Thank you! :)
